{% set name = "requests_oauth2client" %}
{% set version = "1.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/requests_oauth2client-{{ version }}.tar.gz
  sha256: 06d10728d58fec4ae5e4b9ce3bbbbef8565817bc3bfacce3edde9ef18f21fc32

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8
    - requests >=2.19.0
    - binapy >=0.8
    - furl >=2.1.2
    - jwskate >=0.11.1
    - attrs >=23.2.0

test:
  imports:
    - requests_oauth2client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/guillp/requests_oauth2client
  summary: An OAuth2.x client based on `requests`.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - melonhead901
